"""usage accounting fields and cancelled status

Revision ID: fc89b2108f89
Revises: d2b5346b2c7c
Create Date: 2026-10-04 15:56:33.760835

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc89b2108f89"
down_revision: Union[str, Sequence[str], None] = "d2b5346b2c7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_constraint(op.f("ck_usage_logs_status"), "usage_logs", type_="check")
    op.create_check_constraint(
        op.f("ck_usage_logs_status"),
        "usage_logs",
        "status IN ('success', 'error', 'cancelled')",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usage_logs", sa.Column("upstream_model", sa.Text(), nullable=True))
    op.add_column(
        "usage_logs", sa.Column("reasoning_tokens", sa.Integer(), nullable=True)
    )
    op.add_column("usage_logs", sa.Column("ttft_ms", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f("ck_usage_logs_status"), "usage_logs", type_="check")
    # The old schema has no cancelled state; retain those rows as errors.
    op.execute("UPDATE usage_logs SET status = 'error' WHERE status = 'cancelled'")
    op.create_check_constraint(
        op.f("ck_usage_logs_status"), "usage_logs", "status IN ('success', 'error')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usage_logs", "ttft_ms")
    op.drop_column("usage_logs", "reasoning_tokens")
    op.drop_column("usage_logs", "upstream_model")
    # ### end Alembic commands ###
